CREATE TABLE
    IF NOT EXISTS player (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        character_id TEXT,
        total_points INTEGER DEFAULT 0,
        xp INTEGER DEFAULT 0,
        power INTEGER DEFAULT 0,
        hability INTEGER DEFAULT 0,
        resistance INTEGER DEFAULT 0,
        ap_current INTEGER DEFAULT 0,
        mp_current INTEGER DEFAULT 0,
        hp_current INTEGER DEFAULT 0,
        notes TEXT,
        weapon_id TEXT,
        master_editing BOOLEAN DEFAULT 0,
        skills_data TEXT,
        hp_max INTEGER DEFAULT 0,
        strength INTEGER DEFAULT 10,
        dexterity INTEGER DEFAULT 10,
        constitution INTEGER DEFAULT 10,
        intelligence INTEGER DEFAULT 10,
        wisdom INTEGER DEFAULT 10,
        charisma INTEGER DEFAULT 10
    );