CREATE TABLE IF NOT EXISTS player_skills (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    player_id INTEGER NOT NULL,
    skill_id TEXT NOT NULL,
    slot INTEGER,
    FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE
);
