/**
 * Battle log event types for player state updates
 */

export const FIGHT_EVENTS = new Set([
  "ADD_CHARACTER",
  "REMOVE_CHARACTER",
  "SET_INITIATIVE",
  "INITIATIVES_REORDERED",
  "BATTLE_STARTED",
  "BATTLE_FINISHED",
  "TURN_ENDED",
  "TURN_ADDED",
  "TURN_DELAYED",
  "TURNS_REORDERED",
  "ALLOW_COUNTER",
  "STATUS_ADDED",
  "STATUS_REMOVED",
  "STATUS_EXTENDED",
  "ATTACK_PENDING",
  "COUNTER_RESOLVED",
  "DAMAGE_DEALT",
  "STATUS_RESOLVED",
  "HP_CHANGED",
  "MAX_HP_CHANGED",
  "MP_CHANGED",
  "MP_RECOVERED",
  "AP_CHANGED",
  "GRADIENT_CHANGED",
  "STAINS_CHANGED",
  "STANCE_CHANGED",
  "RANK_CHANGED",
  "FLEEING",
  "HEAL_APPLIED",
  "STATUS_CLEANSED",
  "BREAK_APPLIED",
  "AUTO_DEATH",
  "PICTO_EFFECT_TRACKED",
  "PICTO_EFFECTS_CLEARED",
  "PICTO_EFFECTS_RESET"
]);

export const SHEET_EVENTS = new Set([
  "ATTACK_PENDING",
  "COUNTER_RESOLVED",
  "DAMAGE_DEALT",
  "STATUS_ADDED",
  "STATUS_RESOLVED",
  "BATTLE_FINISHED",
  "HEAL_APPLIED",
  "STATUS_CLEANSED",
  "BREAK_APPLIED",
  "HP_CHANGED",
  "MAX_HP_CHANGED",
  "MP_CHANGED",
  "AP_CHANGED",
  "RANK_CHANGED"
]);
